[build]
  publish = "_site"

  # Allows overriding metadata.json via env var

  command = "[ \"$METADATA_JSON\" ] && echo $METADATA_JSON > _data/metadata.json; npm run build-ci"
  functions = "functions/"

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"

[dev]
[dev.https]
certFile = "../../localhost.pem"
keyFile = "../../localhost-key.pem"